var NumberOfWords = 95

var words = new BuildArray(NumberOfWords)

// Use the following variables to 
// define your random words:
words[1] = "Activity: Brushing teeth"
words[2] = "Activity: Building a sandcastle"
words[3] = "Activity: Dancing"
words[4] = "Activity: Driving a car"
words[5] = "Activity: Opening a gift"
words[6] = "Activity: Playing baseball"
words[7] = "Activity: Shoveling snow"
words[8] = "Activity: Swimming"
words[9] = "Activity: Skateboarding"
words[10] = "Activity: Tying a shoe"
words[11] = "Activity: Walking a dog"
words[12] = "Activity: Yoga"
words[13] = "Animal: Bumblebee"
words[14] = "Animal: Bird"
words[15] = "Animal: Cat"
words[16] = "Animal: Cow"
words[17] = "Animal: Dog"
words[18] = "Animal: Fish"
words[19] = "Animal: Giraffe"
words[20] = "Animal: Horse"
words[21] = "Animal: Monkey"
words[22] = "Animal: Rabbit"
words[23] = "Animal: Spider"
words[24] = "Animal: Snake"
words[25] = "Book: Alice's Adventures in Wonderland"
words[26] = "Book: Angelina Ballerina"
words[27] = "Book: Captain Underpants"
words[28] = "Book: Diary of a Wimpy Kid"
words[29] = "Book: Harry Potter and the Sorcerer's Stone"
words[30] = "Book: The Cat in the Hat"
words[31] = "Book: The Giving Tree"
words[32] = "Book: The Gruffalo"
words[33] = "Book: The Very Hungry Caterpillar"
words[34] = "Book: Where the Wild Things Are"
words[35] = "Fairy Tale: Beauty and the Beast"
words[27] = "Fairy Tale: Chicken Little"
words[28] = "Fairy Tale: Cinderella"
words[29] = "Fairy Tale: Goldilocks and The Three Bears"
words[30] = "Fairy Tale: Little Red Riding Hood"
words[31] = "Fairy Tale: Rapunzel"
words[32] = "Fairy Tale: Snow White and the Seven Dwarves"
words[33] = "Fairy Tale: Sleeping Beauty"
words[34] = "Fairy Tale: The Boy Who Cried Wolf"
words[35] = "Fairy Tale: The Emperor's New Clothes"
words[36] = "Food: Banana"
words[37] = "Food: Bubblegum"
words[38] = "Food: French fries"
words[39] = "Food: Ice cream cone"
words[40] = "Food: Jelly"
words[41] = "Food: Pizza"
words[42] = "Food: Popcorn"
words[43] = "Food: Sandwich"
words[44] = "Food: Spaghetti"
words[45] = "Food: Taco"
words[46] = "Food: Ramen"
words[47] = "Food: Sushi"
words[48] = "Food: Daifuku"
words[49] = "Birds can sing"
words[50] = "Movie: Boss Baby"
words[51] = "Movie: Pets"
words[52] = "Movie: Finding Nemo"
words[53] = "Movie: Frozen"
words[54] = "Movie: Harry Potter"
words[55] = "Movie: Moana"
words[56] = "Movie: Pirates of the Caribbean"
words[57] = "Movie: Spiderman"
words[58] = "Movie: Superman"
words[59] = "Movie: The Jungle Book"
words[60] = "Movie: The Lego Movie"
words[61] = "Movie: The Lion King"
words[62] = "Movie: The Little Mermaid"
words[63] = "Movie: How To Train a Dragon"
words[64] = "Movie: Toy Story"
words[65] = "Movie: Spirited Away"
words[66] = "Movie: Totoro"
words[67] = "Movie: Shrek"
words[68] = "Movie: Despicable Me"
words[69] = "Movie: Kiki's Delivery Service "
words[70] = "Song: Row Row Row Your Boat"
words[71] = "Song: Into the Unknown(Frozen 2) "
words[72] = "Song: I like to move it move it (Madagascar)"
words[73] = "Song: How Far I'll Go (Moana)"
words[74] = "Song: I Just Can't Wait To Be King (Lion King)"
words[75] = "Song: Never had a friend like me (Aladdin)"
words[76] = "Song: Happy Pharrell Williams (Despicable Me 2)"
words[77] = "Song: Everything is Awesome (Lego Movie)"
words[78] = "Song: Do you want to build a snowman? (Frozen)"
words[79] = "Song: Under The Sea (The Little Mermaid)"
words[80] = "Song: Hakuna Matata (Lion King)"
words[81] = "Song: Let it Go (Frozen)"
words[82] = "Song: Twinkle, Twinkle, Little Star"
words[83] = "Song: You are My Sunshine"
words[84] = "Television Show: Peppa Pig"
words[85] = "Television Show: PJMasks"
words[86] = "Television Show: Dora the Explorer"
words[87] = "Television Show: Spongebob Squarepants"
words[88] = "Television Show: Pokemon"
words[89] = "Television Show: Pocoyo "
words[90] = "Television Show: Minecraft"
words[91] = "Television Show: Yugioh"
words[92] = "Television Show: Adventure Time"
words[93] = "Television Show: PawPatrol"
words[94] = "Television Show: Dinosaur King"
words[95] = "Television Show: Hello Kitty"


function BuildArray(size){
this.length = size
for (var i = 1; i <= size; i++){
this[i] = null}
return this
}

function PickRandomWord(frm) {
// Generate a random number between 1 and NumberOfWords
var rnd = Math.ceil(Math.random() * NumberOfWords)

// Display the word inside the text box
frm.WordBox.value = words[rnd]
}